[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/tags"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "ollama-gpt-oss"
source = "."

[services.variables]
GPT_OSS_MODEL = "gpt-oss:20b"
OLLAMA_HOST = "0.0.0.0"
OLLAMA_PORT = "11434"