[variables]
NIXPACKS_METADATA = "docker"

[phases.setup]
nixPkgs = ["curl", "bash"]

[phases.install]
cmds = [
  "curl -fsSL https://ollama.com/install.sh | sh"
]

[phases.build]
cmds = [
  "chmod +x start.sh",
  "echo 'Ollama installation completed'"
]

[start]
cmd = "bash start.sh"